use colored::*;

pub fn print_startup_banner() {
    let separator = "=".repeat(96);
    let title = "MINUTEMAN 0.1 // WIRELESS SIGNALS ANALYSIS AND NETWORK INTERROGATION UTILITY";
    
    let warning_paragraph = 
"CRITICAL LEGAL AND REGULATORY COMPLIANCE WARNING:

THIS TOOL IS DESIGNED FOR AUTHORIZED LABORATORY RESEARCH ENVIRONMENTS AND CONTROLLED TECHNICAL TESTBEDS ONLY. IT IS STRICTLY PROHIBITED TO USE THIS SOFTWARE FOR MONITORING, INTERCEPTING, OR ANALYZING WIRELESS COMMUNICATIONS ON NETWORKS OR DEVICES WITHOUT EXPLICIT WRITTEN AUTHORIZATION FROM THE NETWORK OPERATORS AND DEVICE OWNERS. UNAUTHORIZED USE MAY VIOLATE FEDERAL AND STATE LAWS INCLUDING THE ELECTRONIC COMMUNICATIONS PRIVACY ACT, COMPUTER FRAUD AND ABUSE ACT, AND VARIOUS STATE WIRETAP STATUTES. VIOLATIONS MAY RESULT IN SEVERE CIVIL AND CRIMINAL PENALTIES INCLUDING FINES AND IMPRISONMENT. BY PROCEEDING, YOU CERTIFY THAT YOU HAVE THE NECESSARY AUTHORIZATION TO OPERATE THIS TOOL IN YOUR ENVIRONMENT AND ACCEPT FULL LEGAL RESPONSIBILITY FOR ALL ACTIONS.";

    println!("\n{}", separator.red().bold());
    println!("{}", title.white().bold());
    println!("{}", separator.red().bold());
    println!("\n{}\n", warning_paragraph.yellow().bold());
    println!("{}", separator.red().bold());
    println!();
}
